name: SpawnCore
main: LaigelPlayz\SpawnCore\main
api: 3.15.0
author: LaigelPlayz
version: 1.0

commands: 
 spawn:
  description: "Teleport to server spawn"
 hub:
  description: "Teleport to server spawn"
 lobby:
  description: "Teleport to server Spawn"
 feed:
  description: "Feed Your Self"
   permission: cmd.feed
    default: op
 regen:
  description: "Regenerate your self"
   permission: cmd.regen
    default: op
